//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlants.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPlants.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string NavMenu_About {
            get {
                return ResourceManager.GetString("NavMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plants.
        /// </summary>
        public static string NavMenu_Plants {
            get {
                return ResourceManager.GetString("NavMenu_Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string NavMenu_Settings {
            get {
                return ResourceManager.GetString("NavMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add plant.
        /// </summary>
        public static string Plants_AddPlant {
            get {
                return ResourceManager.GetString("Plants_AddPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Archive.
        /// </summary>
        public static string Plants_Archive {
            get {
                return ResourceManager.GetString("Plants_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Plants_Cancel {
            get {
                return ResourceManager.GetString("Plants_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date planted.
        /// </summary>
        public static string Plants_DatePlanted {
            get {
                return ResourceManager.GetString("Plants_DatePlanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Plants_Description {
            get {
                return ResourceManager.GetString("Plants_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details.
        /// </summary>
        public static string Plants_Details {
            get {
                return ResourceManager.GetString("Plants_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Plants_Edit {
            get {
                return ResourceManager.GetString("Plants_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last watered.
        /// </summary>
        public static string Plants_LastWatered {
            get {
                return ResourceManager.GetString("Plants_LastWatered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are {0} days.
        /// </summary>
        public static string Plants_LastWatered_DaysAgo {
            get {
                return ResourceManager.GetString("Plants_LastWatered_DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Never.
        /// </summary>
        public static string Plants_LastWatered_Never {
            get {
                return ResourceManager.GetString("Plants_LastWatered_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Today.
        /// </summary>
        public static string Plants_LastWatered_Today {
            get {
                return ResourceManager.GetString("Plants_LastWatered_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yesterday.
        /// </summary>
        public static string Plants_LastWatered_Yesterday {
            get {
                return ResourceManager.GetString("Plants_LastWatered_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No plants found.
        /// </summary>
        public static string Plants_NoPlants {
            get {
                return ResourceManager.GetString("Plants_NoPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plants.
        /// </summary>
        public static string Plants_Plants {
            get {
                return ResourceManager.GetString("Plants_Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Plants_Save {
            get {
                return ResourceManager.GetString("Plants_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Species.
        /// </summary>
        public static string Plants_Species {
            get {
                return ResourceManager.GetString("Plants_Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plants.
        /// </summary>
        public static string Plants_TitlePage {
            get {
                return ResourceManager.GetString("Plants_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Water.
        /// </summary>
        public static string Plants_Water {
            get {
                return ResourceManager.GetString("Plants_Water", resourceCulture);
            }
        }
    }
}
